#!/usr/bin/env bash
# Tests for the Makefile itself: things that could turn `make check` green
# without touching a recipe.
source "$(dirname "$0")/lib.sh"

# GOFLAGS in the environment could filter tests (-run) or skip slow ones (-short).
test_goflags_from_environment_cannot_filter_tests() {
  local out rc=0
  out="$(cd "$REPO_DIR" && GOFLAGS='-run=^NoSuchTest$' make -s test 2>&1)" || rc=$?
  assert_eq "$rc" "0" "make test con GOFLAGS en el entorno ($out)"
  assert_not_contains "$out" "no tests to run" "GOFLAGS del entorno no llega a go test"
}

# GOFLAGS written with `go env -w` lives in the go env file, not in the
# environment: make test refuses to run instead of silently obeying it.
test_goflags_in_go_env_file_fails() {
  GOENV="$T/goenv" go env -w GOFLAGS=-short
  local out rc=0
  out="$(cd "$REPO_DIR" && GOENV="$T/goenv" make -s test 2>&1)" || rc=$?
  assert_eq "$rc" "2" "make test con GOFLAGS en go env"
  assert_contains "$out" "GOFLAGS no vacío"
}

# go_module <dir>: a throwaway module to run the repo's Makefile targets on,
# with `make -f`, so the test never touches the repo.
# golangci_lint_path: the pinned golangci-lint of the Makefile, relative to the repo.
golangci_lint_path() {
  make -s --no-print-directory -C "$REPO_DIR" -f "$REPO_DIR/Makefile" print-GOLANGCI_LINT
}

go_module() {
  mkdir -p "$1/pkg/demo"
  printf 'module example.invalid/demo\n\ngo 1.27.1\n' > "$1/go.mod"
  printf 'package demo\n\nfunc Demo() int { return 1 }\n' > "$1/pkg/demo/demo.go"
}

test_fmt_check_fails_on_unformatted_go() {
  go_module "$T/m"
  printf 'package demo\nfunc   Bad( )int{\nreturn 1}\n' > "$T/m/pkg/demo/bad.go"
  local out rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" fmt-check 2>&1)" || rc=$?
  assert_eq "$rc" "2" "fmt-check con un .go sin formatear"
  assert_contains "$out" "pkg/demo/bad.go"
}

# lint runs the pinned golangci-lint with the repo config (E1 step 1.1): an
# unchecked error fails, and so does a //nolint that names no linter.
test_lint_runs_golangci_lint_with_the_repo_config() {
  local gl
  gl="$REPO_DIR/$(golangci_lint_path)"
  go_module "$T/m"
  cp "$REPO_DIR/.golangci.yml" "$T/m/"
  printf 'package demo\n\nfunc f() error { return nil }\n\nfunc G() { f() }\n' > "$T/m/pkg/demo/unchecked.go"
  local out rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" lint GOLANGCI_LINT="$gl" HARNESS_SCRIPTS= 2>&1)" || rc=$?
  assert_eq "$rc" "2" "lint con un error sin comprobar"
  assert_contains "$out" "unchecked.go:5"
  assert_contains "$out" "(errcheck)"
  printf 'package demo\n\nfunc f() error { return nil }\n\nfunc G() { f() } //nolint // F-0001\n' > "$T/m/pkg/demo/unchecked.go"
  rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" lint GOLANGCI_LINT="$gl" HARNESS_SCRIPTS= 2>&1)" || rc=$?
  assert_eq "$rc" "2" "lint con un //nolint sin linter"
  assert_contains "$out" "(nolintlint)"
  # A generated-code header would switch every linter off in that file (review
  # round 1 of E1 step 1.1): the config does not exclude generated files.
  printf '// Code generated by hand. DO NOT EDIT.\n\npackage demo\n\nfunc f() error { return nil }\n\nfunc G() { f() }\n' > "$T/m/pkg/demo/unchecked.go"
  rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" lint GOLANGCI_LINT="$gl" HARNESS_SCRIPTS= 2>&1)" || rc=$?
  assert_eq "$rc" "2" "lint con una cabecera de código generado"
  assert_contains "$out" "(errcheck)"
  # Overlapping runs (the Stop hook and a reviewer's clone) wait for the lock
  # instead of failing (review round 1 of E1 step 1.1).
  out="$(make -s -n -C "$REPO_DIR" -f "$REPO_DIR/Makefile" lint 2>&1)"
  assert_contains "$out" "run --config .golangci.yml --allow-serial-runners ./..."
  # Only the pinned .golangci.yml counts: a .golangci.yaml, .toml or .json
  # next to it would take precedence (review round 2 of E1 step 1.1).
  printf 'version: "2"\nlinters:\n  default: none\n  enable:\n    - govet\n' > "$T/m/.golangci.yaml"
  printf 'package demo\n\nfunc f() error { return nil }\n\nfunc G() { f() }\n' > "$T/m/pkg/demo/unchecked.go"
  rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" lint GOLANGCI_LINT="$gl" HARNESS_SCRIPTS= 2>&1)" || rc=$?
  assert_eq "$rc" "2" "lint con un .golangci.yaml que apaga errcheck"
  assert_contains "$out" "(errcheck)"
}

# What lint checks is defined by .golangci.yml, so its content is pinned like
# ci.yml (L-006): switching a linter off shows in the diff of this test.
test_golangci_config_is_the_reviewed_one() {
  local expected
  expected="$(cat <<'EOF'
# golangci-lint v2 (https://golangci-lint.run/docs/configuration/file/),
# pinned in the Makefile. The standard set plus nolintlint: a //nolint names
# its linter and says why; check-skips.sh also wants an F-NNNN on that line
# (L-003). Generated files are linted too: a "Code generated" header must not
# switch the linters off.
version: "2"
linters:
  default: standard
  enable:
    - nolintlint
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: disable
EOF
)"
  assert_eq "$(cat "$REPO_DIR/.golangci.yml")" "$expected" ".golangci.yml es el revisado"
}

test_fmt_check_skips_testdata_fixtures() {
  go_module "$T/m"
  mkdir -p "$T/m/pkg/demo/testdata"
  printf 'package fixture\nfunc   Trap( ){}\n' > "$T/m/pkg/demo/testdata/trap.go"
  local out rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" fmt-check 2>&1)" || rc=$?
  assert_eq "$rc" "0" "fixtures sin formatear en testdata ($out)"
}

test_test_target_fails_on_red_go_test() {
  go_module "$T/m"
  printf 'package demo\n\nimport "testing"\n\nfunc TestRed(t *testing.T) { t.Fatal("rojo") }\n' > "$T/m/pkg/demo/demo_test.go"
  local out rc=0
  out="$(cd "$T/m" && make -s -f "$REPO_DIR/Makefile" test 2>&1)" || rc=$?
  assert_eq "$rc" "2" "make test con un test Go en rojo"
  assert_contains "$out" "--- FAIL: TestRed"
}

# E0 closing review (integration, finding 13): make install-hooks puts the same
# pre-push and commit-msg as scripts/harness/ into the repo's hooks directory.
test_install_hooks_installs_both_hooks() {
  init_repo "$T/repo"
  mkdir -p "$T/repo/scripts/harness"
  cp "$REPO_DIR/scripts/harness/pre-push" "$REPO_DIR/scripts/harness/commit-msg" "$T/repo/scripts/harness/"
  local out rc=0 h
  out="$(cd "$T/repo" && make -s -f "$REPO_DIR/Makefile" install-hooks 2>&1)" || rc=$?
  assert_eq "$rc" "0" "make install-hooks ($out)"
  for h in pre-push commit-msg; do
    cmp -s "$T/repo/.git/hooks/$h" "$REPO_DIR/scripts/harness/$h" || fail "$h no está instalado igual que scripts/harness/$h"
    [ -x "$T/repo/.git/hooks/$h" ] || fail "$h instalado sin permiso de ejecución"
  done
}

# F-0014: the required check runs `make check` as the pull request defines it,
# so every check of the harness stays among its prerequisites.
test_check_runs_every_harness_check() {
  local check gate phony t missing=""
  check="$(grep -E '^check:' "$REPO_DIR/Makefile")"
  gate="$(grep -E '^gate:' "$REPO_DIR/Makefile")"
  assert_eq "$check" \
    "check: weakeners pipes fallos skips attribution personal fmt-check lint test determinism test-harness secrets" "prerrequisitos de check"
  assert_eq "$gate" "gate: check evals-paso e2e-rapido" "prerrequisitos de gate"
  # Round 2 of step 0.4: a target missing from .PHONY is skipped when a path
  # with its name exists (a test/ directory), and check still says OK.
  phony="$(awk '/^\.PHONY:/ {p = 1} p {printf " %s", $0} p && !/\\$/ {p = 0}' "$REPO_DIR/Makefile")"
  phony="${phony//\\/ }"
  phony="${phony//$'\t'/ } "
  for t in check gate ${check#check:} ${gate#gate:}; do
    [[ "$phony" == *" $t "* ]] || missing+="$t "
  done
  assert_eq "$missing" "" "objetivos de check y gate fuera de .PHONY"
}

run_tests "$@"
